//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İsKarti.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblGorev
    {
        public int GorevID { get; set; }
        public string GorevAdi { get; set; }
        public Nullable<int> GorevSahip { get; set; }
        public string Aciklama { get; set; }
        public string Notlar { get; set; }
        public Nullable<System.DateTime> GorevTarih { get; set; }
        public Nullable<System.DateTime> TahminDate { get; set; }
        public Nullable<System.DateTime> GercekDate { get; set; }
        public Nullable<int> DurumID { get; set; }
    
        public virtual TblDurums TblDurums { get; set; }
        public virtual TblKullanici TblKullanici { get; set; }
    }
}
